<a href="https://colab.research.google.com/github/dangcute/laptrinhdulieu/blob/main/Baitap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
q=[29, 32, 46,8]
print(len(q))

4


In [ ]:
y=[12, 1, 16, 1]
y=list(reversed(y))
print(y)

[1, 16, 1, 12]


In [ ]:
foo =[6.5, "A", "B", 'thu', -7]
foo[1:3]=[2.75, -1.5]
print(foo)

[6.5, 2.75, -1.5, 'thu', -7]


In [ ]:
import numpy as np
x = np.array([6, 1, 9, 9, 3])
bool_x = x > 5
print(bool_x)

[ True False  True  True False]


In [ ]:
q= 0.26994
print(round(q, 0))

0.0


In [ ]:
q = [36, 15, 12, 38]
print(q[-2])

12


In [ ]:
q= 9.87048
print(round(q, 0))

10.0


In [ ]:
x=[6, 2, 7, 19, 7, 14, 0]
print(x[-3] + x[-4])

26


In [ ]:
import numpy as np
z = np.array([[5, 0, 2], [3, 1, 1]])
print(z[0:, 1:])

[[0 2]
 [1 1]]


In [ ]:
import numpy as np
z= np.array([[8, 6, 6], [6, 4, 2]])
print(z[1:, 2:])

[[2]]


In [ ]:
x = ['u', 'c', 'w', 'b', 'v', 'i']
print(x[1:5])

['c', 'w', 'b', 'v']


In [ ]:
import numpy as np
z = np.array([[8, 14, 21], [5, 16, 20]])
print(z[1] [2])

20


In [ ]:
import numpy as np
np.array([26, 28, 18, 22])

array([26, 28, 18, 22])

In [ ]:
import numpy as np
p= np.array([15,2,18,15,7,8])
print(p[0])

15


In [ ]:
q=[36]
print(len(q))

1


In [ ]:
import numpy as np
z= np.array([[2,3,3], [4,6,9]])
print(z[0:, 2:])

[[3]
 [9]]


In [ ]:
a=[9.93, 5.92,5.44]
b=['k','j','k']
c=[1,1,7]
print([c,b,a])

[[1, 1, 7], ['k', 'j', 'k'], [9.93, 5.92, 5.44]]


In [ ]:
import numpy as np
m= np.array([2,4,6])
n=2
print(m-n)

[0 2 4]


In [ ]:
p=['l','f','x','o','e','q']
del(p[4])
print(p)

['l', 'f', 'x', 'o', 'q']


In [ ]:
p=[[20,"a","b"],["c",22,18],["d","e","f"]]
print(p[1][:1])

['c']


In [ ]:
import numpy as np
z= np.array([[4,3,5], [5,8,3]])
print(z[1, 0])

5


In [ ]:
q=6.02093
print(round(q,3))

6.021


In [ ]:
y=[3,3,16,4]
y.append(9)
print(y)

[3, 3, 16, 4, 9]


In [ ]:
x=[False, True, '2', 3.0]
print(type(x))

<class 'list'>


In [ ]:
import numpy as np
x= np.array([2,12,11,0,6,8])
print(x[1:3])

[12 11]


In [ ]:
p=6
q="p is:"
print(q+ str(p))

p is:6


In [ ]:
foo=[0, 5.22, "A", "Tue", 1.2]
foo[0:2]='e', 'f'
print(foo)

['e', 'f', 'A', 'Tue', 1.2]
